export const TARGET_TYPE = {
  POST: 'POST',
  COMMENT: 'COMMENT',
  USER: 'USER',
  MEDIA: 'MEDIA',
} as const;

export const ACTION_TYPE = {
  POST_CREATED: 'POST_CREATED',
  POST_SUBMITTED: 'POST_SUBMITTED',
  POST_UPDATED: 'POST_UPDATED',
  MODERATION_STATUS_CHANGED: 'MODERATION_STATUS_CHANGED',
} as const;

export const POST_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
