export const ERROR_MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  USER_UNAUTHORIZED: 'User unauthorized',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_OR_EXPIRED_TOKEN: 'Invalid or expired token',
  VERSION_NOT_FOUND: 'This version does not exist',
  EMAIL_EXISTS: 'Email already exists',
  PROFILE_NOT_FOUND: 'Profile not found',
  PROFILE_EXISTS: 'Profile already exists',
  USERNAME_EXISTS: 'Username already exists',
  POST_HISTORY_NOT_FOUND: 'Post history not found',
  POST_NOT_FOUND: 'Post not found',
  POST_SLUG_ALREADY_EXISTS: 'Post with this slug already exists',
  ROLE_NOT_FOUND: 'Role not found',
  ROLE_EXISTS: 'Role already exists',
  INVALID_ROLE: 'Invalid role',
  USER_HAS_ROLE: 'User already has this role',
  AUTHOR_NOT_FOUND: 'Author not found',
  AUTHOR_EXISTS: 'Author already exists',
  IMAGE_NOT_FOUND: 'Image not found',
  IMAGE_EXISTS: 'Image already exists',
  IMAGE_DELETE_FAILED: 'Image delete failed',
  NOT_POST_AUTHOR: 'You are not the main author of this post',
} as const;
