import { Response } from 'express';

import { JwtPayloadType } from '@/shared/types/jwt-payload';
import { normalizeEmail } from '@/shared/utils/normalizeEmail';
import { Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { User } from '@prisma/client';

import { UsersService } from '../users/users.service';
import { RegisterDto } from './dto/register.dto';
import { EmailService } from './services/email/email.service';
import { PasswordService } from './services/password/password.service';

@Injectable()
export class AuthService {
  private readonly ACCESS_TOKEN_OPTIONS = {
    httpOnly: true,
    secure: true,
  };

  constructor(
    private readonly usersService: UsersService,
    private readonly passwordService: PasswordService,
    private readonly emailService: EmailService,
    private readonly jwt: JwtService,
    private readonly config: ConfigService,
  ) {}

  public async register(
    { email, password }: RegisterDto,
    res: Response,
  ): Promise<{ accessToken: string; refreshToken: string }> {
    await this.usersService.isEmailExist(email);
    const hashedPassword = await this.passwordService.hash(password);

    const createdUser = await this.usersService.createOne({ email: normalizeEmail(email), hashedPassword });

    return this.generateTokens(createdUser.id, res);
  }

  public async login(
    { email, password }: RegisterDto,
    res: Response,
  ): Promise<{ accessToken: string; refreshToken: string }> {
    const user = await this.validateUser(email, password);

    if (!user) {
      throw new NotFoundException();
    }

    return this.generateTokens(user.id, res);
  }

  public async googleAuth(email: string, res: Response): Promise<{ accessToken: string; refreshToken: string }> {
    const normalizedEmail = normalizeEmail(email);
    const user = await this.usersService.getOne({ email: normalizedEmail });

    if (user) {
      return this.generateTokens(user.id, res);
    }

    const autoGeneratedPassword = this.passwordService.generatePassword();
    const hashedPassword = await this.passwordService.hash(autoGeneratedPassword);

    const createdUser = await this.usersService.createOne({ email: normalizedEmail, hashedPassword });
    await this.emailService.sendWelcomeEmail(email, autoGeneratedPassword);

    return this.generateTokens(createdUser.id, res);
  }

  public async requestPasswordChange(email: string): Promise<void> {
    const user = await this.usersService.getOne({ email: normalizeEmail(email) });
    if (!user) {
      throw new NotFoundException('User not found');
    }

    const token = await this.generatePasswordResetToken(user.id);
    await this.emailService.sendPasswordChangeInstructions(email, token);
  }

  public async resetPassword(token: string, newPassword: string): Promise<void> {
    const userId = await this.validatePasswordResetToken(token);
    const hashedPassword = await this.passwordService.hash(newPassword);

    await this.usersService.updateOne({ hashedPassword }, +userId);
  }

  private async generatePasswordResetToken(userId: number): Promise<string> {
    const payload = { userId };
    return this.jwt.signAsync(payload, {
      secret: this.config.getOrThrow('JWT_PASSWORD_RESET_SECRET'),
      expiresIn: this.config.getOrThrow('JWT_PASSWORD_RESET_EXPIRES'),
    });
  }

  private async validatePasswordResetToken(token: string): Promise<string> {
    try {
      const payload = await this.jwt.verifyAsync<JwtPayloadType>(token, {
        secret: this.config.getOrThrow('JWT_PASSWORD_RESET_SECRET'),
      });
      return payload.userId;
    } catch (error) {
      throw new UnauthorizedException('Invalid or expired token');
    }
  }

  public async validateUser(email: string, pass: string): Promise<User | null> {
    const user = await this.usersService.getOne({ email: normalizeEmail(email) });

    if (!user) {
      return null;
    }

    const isPasswordValid = await this.passwordService.verify(pass, user.hashedPassword);

    return isPasswordValid ? user : null;
  }

  public async generateTokens(userId: number, res: Response): Promise<{ accessToken: string; refreshToken: string }> {
    const [accessToken, refreshToken] = await Promise.all([
      this.generateToken(userId, 'JWT_ACCESS_SECRET', 'JWT_ACCESS_EXPIRES'),
      this.generateToken(userId, 'JWT_REFRESH_SECRET', 'JWT_REFRESH_EXPIRES'),
    ]);

    res.cookie('refreshToken', refreshToken, this.ACCESS_TOKEN_OPTIONS);

    return { accessToken, refreshToken };
  }

  private async generateToken(userId: number, secretKey: string, expiresKey: string): Promise<string> {
    return this.jwt.signAsync(
      { userId },
      {
        secret: this.config.getOrThrow(secretKey),
        expiresIn: this.config.getOrThrow(expiresKey),
      },
    );
  }
}
