import { Response } from 'express';

import { User } from '@/generated/prisma';
import { PrismaService } from '@/prisma/prisma.service';
import { ERROR_MESSAGES } from '@/shared/constants/error-message';
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';

import { UsersService } from '../users/users.service';
import { AuthDto } from './dto/auth.dto';
import { ResetPasswordDto } from './dto/reset-password.dto';
import { TokensDto } from './dto/tokens.dto';
import { EmailService } from './services/email/email.service';
import { PasswordService } from './services/password/password.service';
import { TokenService } from './services/token/token.service';

@Injectable()
export class AuthService {
  private readonly COOKIE_REFRESH_TOKEN_OPTIONS = {
    httpOnly: true,
    secure: true,
  };

  constructor(
    private readonly usersService: UsersService,
    private readonly passwordService: PasswordService,
    private readonly emailService: EmailService,
    private readonly tokenService: TokenService,
    private readonly prisma: PrismaService,
  ) {}

  public async register({ email, password }: AuthDto, res: Response): Promise<TokensDto> {
    await this.usersService.isEmailExist(email);
    const hashedPassword = await this.passwordService.hash(password);
    const createdUser = await this.usersService.createOne({ email, hashedPassword });

    return this.generateAndSetTokens(createdUser.id, res);
  }

  public async login({ email, password }: AuthDto, res: Response): Promise<TokensDto> {
    const user = await this.validateUser(email, password);
    return this.generateAndSetTokens(user.id, res);
  }

  public async refreshTokens(userId: number, res: Response): Promise<TokensDto> {
    const user = await this.usersService.getOne({ id: userId });

    return this.generateAndSetTokens(user.id, res);
  }

  public async googleAuth(email: string, res: Response): Promise<TokensDto> {
    const normalizedEmail = email;
    const user = await this.usersService.getOne({ email: normalizedEmail });

    if (user) {
      return this.generateAndSetTokens(user.id, res);
    }

    const autoGeneratedPassword = this.passwordService.generatePassword();
    const hashedPassword = await this.passwordService.hash(autoGeneratedPassword);
    const createdUser = await this.usersService.createOne({ email: normalizedEmail, hashedPassword });
    await this.emailService.sendWelcomeEmail(email, autoGeneratedPassword);

    return this.generateAndSetTokens(createdUser.id, res);
  }

  public async requestPasswordChange(email: string): Promise<void> {
    const user = await this.usersService.getOne({ email });

    if (!user) {
      throw new NotFoundException(ERROR_MESSAGES.USER_NOT_FOUND);
    }

    const passwordResetToken = await this.tokenService.generatePasswordResetToken(user.id);
    await this.emailService.sendPasswordChangeInstructions(email, passwordResetToken);
  }

  public async resetPassword({ passwordResetToken, newPassword }: ResetPasswordDto): Promise<void> {
    const payload = await this.tokenService.verifyToken(passwordResetToken, 'JWT_PASSWORD_RESET_SECRET');
    const hashedPassword = await this.passwordService.hash(newPassword);
    await this.usersService.updateOne({ where: { id: +payload.userId }, data: { hashedPassword } });
  }

  private async validateUser(email: string, pass: string): Promise<User> {
    const user = await this.prisma.user.findFirst({ where: { email } });

    if (!user) {
      throw new NotFoundException(ERROR_MESSAGES.USER_NOT_FOUND);
    }

    if (!(await this.passwordService.verify(pass, user.hashedPassword))) {
      throw new BadRequestException(ERROR_MESSAGES.INVALID_CREDENTIALS);
    }

    return user;
  }

  private async generateAndSetTokens(userId: number, res: Response): Promise<TokensDto> {
    const tokens = await this.tokenService.generateAuthTokens(userId);
    res.cookie('refreshToken', tokens.refreshToken, this.COOKIE_REFRESH_TOKEN_OPTIONS);
    return tokens;
  }
}
